// Autogenerated AST node
package org.python.antlr.ast;
import org.antlr.runtime.CommonToken;
import org.antlr.runtime.Token;
import org.python.antlr.AST;
import org.python.antlr.PythonTree;
import org.python.antlr.adapter.AstAdapters;
import org.python.antlr.base.excepthandler;
import org.python.antlr.base.expr;
import org.python.antlr.base.mod;
import org.python.antlr.base.slice;
import org.python.antlr.base.stmt;
import org.python.core.ArgParser;
import org.python.core.AstList;
import org.python.core.Py;
import org.python.core.PyObject;

import org.python.core.PyUnicode;
import org.python.core.PyStringMap;
import org.python.core.PyType;
import org.python.core.Visitproc;
import org.python.expose.ExposedGet;
import org.python.expose.ExposedMethod;
import org.python.expose.ExposedNew;
import org.python.expose.ExposedSet;
import org.python.expose.ExposedType;
import java.io.DataOutputStream;
import java.io.IOException;
import java.util.ArrayList;
import org.python.core.ASTMatcher;

@ExposedType(name = "_ast.Hole", base = expr.class)
public class Hole extends expr implements Context {
public static final PyType TYPE = PyType.fromClass(Hole.class);
    private Object n;
    public Object getInternalN() {
        return n;
    }
    @ExposedGet(name = "n")
    public PyObject getN() {
        return (PyObject)n;
    }
    @ExposedSet(name = "n")
    public void setN(PyObject n) {
        this.n = AstAdapters.py2object(n);
    }

    private expr_contextType ctx;
    public expr_contextType getInternalCtx() {
        return ctx;
    }
    @ExposedGet(name = "ctx")
    public PyObject getCtx() {
        return AstAdapters.expr_context2py(ctx);
    }
    @ExposedSet(name = "ctx")
    public void setCtx(PyObject ctx) {
        this.ctx = AstAdapters.py2expr_context(ctx);
    }


    private final static PyUnicode[] fields =
    new PyUnicode[] {new PyUnicode("n"), new PyUnicode("ctx")};
    @ExposedGet(name = "_fields")
    public PyUnicode[] get_fields() { return fields; }

    private final static PyUnicode[] attributes =
    new PyUnicode[] {new PyUnicode("lineno"), new PyUnicode("col_offset")};
    @ExposedGet(name = "_attributes")
    public PyUnicode[] get_attributes() { return attributes; }

    public Hole(PyType subType) {
        super(subType);
    }
    public Hole() {
        this(TYPE);
    }
    @ExposedNew
    @ExposedMethod
    public void Hole___init__(PyObject[] args, String[] keywords) {
        ArgParser ap = new ArgParser("Hole", args, keywords, new String[]
            {"n", "ctx", "lineno", "col_offset"}, 2, true);
        setN(ap.getPyObject(0, Py.None));
        setCtx(ap.getPyObject(1, Py.None));
        int lin = ap.getInt(2, -1);
        if (lin != -1) {
            setLineno(lin);
        }

        int col = ap.getInt(3, -1);
        if (col != -1) {
            setLineno(col);
        }

    }

    public Hole(PyObject n, PyObject ctx) {
        setN(n);
        setCtx(ctx);
    }

    public Hole(Token token, Object n, expr_contextType ctx) {
        super(token);
        this.n = n;
        this.ctx = ctx;
    }

    public Hole(Integer ttype, Token token, Object n, expr_contextType ctx) {
        super(ttype, token);
        this.n = n;
        this.ctx = ctx;
    }

    public Hole(PythonTree tree, Object n, expr_contextType ctx) {
        super(tree);
        this.n = n;
        this.ctx = ctx;
    }

    @ExposedGet(name = "repr")
    public String toString() {
        return "Hole";
    }

    public String toStringTree() {
        StringBuffer sb = new StringBuffer("Hole(");
        sb.append("n=");
        sb.append(dumpThis(n));
        sb.append(",");
        sb.append("ctx=");
        sb.append(dumpThis(ctx));
        sb.append(",");
        sb.append(")");
        return sb.toString();
    }

    public <R> R accept(VisitorIF<R> visitor) throws Exception {
        R x = null;
        if (visitor==null){
            new RuntimeException("Unexpected node: " + this);
        }else{
            visitor.preVisit(this);
            x = visitor.visitHole(this);
            visitor.postVisit(this);
        }
        return x;
    }

    public void traverse(VisitorIF<?> visitor) throws Exception {
    }

    public PyObject __dict__;

    @Override
    public PyObject fastGetDict() {
        ensureDict();
        return __dict__;
    }

    @ExposedGet(name = "__dict__")
    public PyObject getDict() {
        return fastGetDict();
    }

    private void ensureDict() {
        if (__dict__ == null) {
            __dict__ = new PyStringMap();
        }
    }

    public void setContext(expr_contextType c) {
        this.ctx = c;
    }

    private int lineno = -1;
    @ExposedGet(name = "lineno")
    public int getLineno() {
        if (lineno != -1) {
            return lineno;
        }
        return getLine();
    }

    @ExposedSet(name = "lineno")
    public void setLineno(int num) {
        lineno = num;
    }

    private int col_offset = -1;
    @ExposedGet(name = "col_offset")
    public int getCol_offset() {
        if (col_offset != -1) {
            return col_offset;
        }
        return getCharPositionInLine();
    }

    @ExposedSet(name = "col_offset")
    public void setCol_offset(int num) {
        col_offset = num;
    }

    @Override
    public int getNodeType(){return HOLE;};

    @Override
    public boolean subtreeMatch(ASTMatcher matcher, Object other) {
        return matcher.match(this, other);
    }


}
